INSERT INTO SAMPLE_ITEM (ID, TITLE, DESCRIPTION, STATUS, CREATED_AT, UPDATED_AT)
VALUES (NEXT VALUE FOR SAMPLE_ITEM_SEQ, 'API test ready', 'CRUD test seed row', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SAMPLE_ITEM (ID, TITLE, DESCRIPTION, STATUS, CREATED_AT, UPDATED_AT)
VALUES (NEXT VALUE FOR SAMPLE_ITEM_SEQ, 'Template sample', 'Second seed row', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TREE_NODE (ID, NODE_KEY, NODE_NAME, PARENT_KEY, LEVEL_NO, SORT_ORDER)
VALUES (NEXT VALUE FOR TREE_NODE_SEQ, 'aaa', 'aaa', NULL, 1, 1);

INSERT INTO TREE_NODE (ID, NODE_KEY, NODE_NAME, PARENT_KEY, LEVEL_NO, SORT_ORDER)
VALUES (NEXT VALUE FOR TREE_NODE_SEQ, 'aaa-1', 'aaa-1', 'aaa', 2, 1);

INSERT INTO TREE_NODE (ID, NODE_KEY, NODE_NAME, PARENT_KEY, LEVEL_NO, SORT_ORDER)
VALUES (NEXT VALUE FOR TREE_NODE_SEQ, 'aaa-1-1', 'aaa-1-1', 'aaa-1', 3, 1);

INSERT INTO TREE_NODE (ID, NODE_KEY, NODE_NAME, PARENT_KEY, LEVEL_NO, SORT_ORDER)
VALUES (NEXT VALUE FOR TREE_NODE_SEQ, 'bbb', 'bbb', NULL, 1, 2);

INSERT INTO GRID_ITEM (ID, NODE_KEY, COL1, COL2, COL3, COL4, COL5, CREATED_AT)
VALUES (NEXT VALUE FOR GRID_ITEM_SEQ, 'aaa-1-1', 'aaa-1-1-col1-001', 'aaa-1-1-col2-001', 'val-001', 'data-A', 'etc-001', CURRENT_TIMESTAMP);

INSERT INTO GRID_ITEM (ID, NODE_KEY, COL1, COL2, COL3, COL4, COL5, CREATED_AT)
VALUES (NEXT VALUE FOR GRID_ITEM_SEQ, 'aaa-1-1', 'aaa-1-1-col1-002', 'aaa-1-1-col2-002', 'val-002', 'data-B', 'etc-002', CURRENT_TIMESTAMP);

INSERT INTO GRID_ITEM (ID, NODE_KEY, COL1, COL2, COL3, COL4, COL5, CREATED_AT)
VALUES (NEXT VALUE FOR GRID_ITEM_SEQ, 'bbb', 'bbb-col1-001', 'bbb-col2-001', 'val-003', 'data-C', 'etc-003', CURRENT_TIMESTAMP);
