CREATE SEQUENCE IF NOT EXISTS SAMPLE_ITEM_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS SAMPLE_ITEM (
    ID NUMBER(19, 0) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    STATUS VARCHAR2(30) DEFAULT 'TODO' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_SAMPLE_ITEM PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS TREE_NODE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS TREE_NODE (
    ID NUMBER NOT NULL,
    NODE_KEY VARCHAR2(50) NOT NULL,
    NODE_NAME VARCHAR2(100) NOT NULL,
    PARENT_KEY VARCHAR2(50),
    LEVEL_NO NUMBER DEFAULT 1 NOT NULL,
    SORT_ORDER NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TREE_NODE PRIMARY KEY (ID),
    CONSTRAINT UQ_TREE_NODE_KEY UNIQUE (NODE_KEY)
);

CREATE SEQUENCE IF NOT EXISTS GRID_ITEM_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS GRID_ITEM (
    ID NUMBER NOT NULL,
    NODE_KEY VARCHAR2(50) NOT NULL,
    COL1 VARCHAR2(100),
    COL2 VARCHAR2(100),
    COL3 VARCHAR2(100),
    COL4 VARCHAR2(100),
    COL5 VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_GRID_ITEM PRIMARY KEY (ID)
);
