CREATE SEQUENCE SAMPLE_ITEM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SAMPLE_ITEM (
    ID NUMBER(19, 0) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    STATUS VARCHAR2(30) DEFAULT 'TODO' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_SAMPLE_ITEM PRIMARY KEY (ID)
);

INSERT INTO SAMPLE_ITEM (ID, TITLE, DESCRIPTION, STATUS, CREATED_AT, UPDATED_AT)
VALUES (SAMPLE_ITEM_SEQ.NEXTVAL, 'API 테스트 준비', 'React 화면에서 목록, 등록, 수정, 삭제를 확인합니다.', 'TODO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SAMPLE_ITEM (ID, TITLE, DESCRIPTION, STATUS, CREATED_AT, UPDATED_AT)
VALUES (SAMPLE_ITEM_SEQ.NEXTVAL, '내부망 템플릿', 'Git으로 내려받아 바로 커스터마이징할 기본 프로젝트입니다.', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
